# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.12.1.dev156+g4f353cc.d20230119'
__version_tuple__ = version_tuple = (0, 12, 1, 'dev156', 'g4f353cc.d20230119')
